MaestroDetalleMVC/MaestroDetalle_MVC/Models/Concepto.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaestroDetalle_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Concepto
    {
        public int IdConcepto { get; set; }
        public int IdVenta { get; set; }
        public int Cantidad { get; set; }
        public string Nombre { get; set; }
        public decimal PrecioUnitario { get; set; }
        public decimal Total { get; set; }
    
        public virtual Venta Venta { get; set; }
    }
}

MaestroDetalleMVC/MaestroDetalle_MVC/Models/MD_Model.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaestroDetalle_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_MaestroDetalleEntities : DbContext
    {
        public BD_MaestroDetalleEntities()
            : base("name=BD_MaestroDetalleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Concepto> Concepto { get; set; }
        public virtual DbSet<Venta> Venta { get; set; }
    }
}

MaestroDetalleMVC/MaestroDetalle_MVC/Models/MD_Model.Designer.cs
// La generación de código T4 está habilitada para el modelo 'C:\Users\lenin\Source\Repos\MVC_MaestroDetalle\MaestroDetalleMVC\MaestroDetalle_MVC\Models\MD_Model.edmx'. 
// Para habilitar la generación de código heredada, cambie el valor de la propiedad del diseñador 'Estrategia de generación de código'
// por 'ObjectContext heredado'. Esta propiedad está disponible en la ventana Propiedades cuando se abre
// el modelo en el diseñador.

// Si no se ha generado ninguna clase de contexto y de entidad, puede que haya creado un modelo vacío pero
// no haya elegido todavía la versión de Entity Framework que se va a usar. Para generar una clase de contexto y clases de entidad
// para el modelo, abra el modelo en el diseñador, haga clic con el botón secundario en la superficie del diseñador y
// seleccione 'Actualizar modelo desde base de datos...', 'Generar base de datos desde modelo...' o 'Agregar elemento de generación
// de código...'.

MaestroDetalleMVC/MaestroDetalle_MVC/Models/MD_Model.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

MaestroDetalleMVC/MaestroDetalle_MVC/Models/Venta.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaestroDetalle_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Venta()
        {
            this.Concepto = new HashSet<Concepto>();
        }
    
        public int IdVenta { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Cliente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Concepto> Concepto { get; set; }
    }
}

MaestroDetalleMVC/MaestroDetalle_MVC/Models/ViewModels/VentaViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MaestroDetalle_MVC.Models.ViewModels
{
    public class VentaViewModel
    {
        public string Cliente { get; set; }
        public List<concepto> Conceptos { get; set; }
    }

    public class concepto
    {
        public int Cantidad { get; set; }
        public string Nombre { get; set; }
        public decimal PrecioUnitario{get;set;}
    }
}

MaestroDetalleMVC/MaestroDetalle_MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MaestroDetalle_MVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MaestroDetalleMVC/MaestroDetalle_MVC/Controllers/MaestroDetalleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MaestroDetalle_MVC.Models.ViewModels;
using MaestroDetalle_MVC.Models;

namespace MaestroDetalle_MVC.Controllers
{
    public class MaestroDetalleController : Controller
    {
        // GET: MaestroDetalle
        public ActionResult Add()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Add(VentaViewModel model)
        {
            try
            {
                using (BD_MaestroDetalleEntities db = new BD_MaestroDetalleEntities())
                {
                    Venta oVenta = new Venta();
                    oVenta.Fecha = DateTime.Now;
                    oVenta.Cliente = model.Cliente;
                    db.Venta.Add(oVenta);
                    db.SaveChanges();

                    foreach (var oC in model.Conceptos)
                    {
                        Concepto oConcepto = new Concepto();
                        oConcepto.Cantidad = oC.Cantidad;
                        oConcepto.Nombre = oC.Nombre;
                        oConcepto.PrecioUnitario = oC.PrecioUnitario;
                        oConcepto.Total = oC.Cantidad * oC.PrecioUnitario;
                        oConcepto.IdVenta = oVenta.IdVenta;
                        db.Concepto.Add(oConcepto);
                    }

                    db.SaveChanges();
                }
                ViewBag.Mesage = "Registro insertado";
                return View();
            }
            catch (Exception)
            {
                return View(model);
            }
        }
    }
}

MaestroDetalleMVC/MaestroDetalle_MVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MaestroDetalleMVC/MaestroDetalle_MVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MaestroDetalleMVC/MaestroDetalle_MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

MaestroDetalleMVC/MaestroDetalle_MVC/Views/MaestroDetalle/Add.cshtml
@model MaestroDetalle_MVC.Models.ViewModels.VentaViewModel

@{
    ViewBag.Title = "Maestro detalle";
}

<h2>@ViewBag.Title</h2>

<div style="color:#00ff21">
    @ViewBag.Mesage
</div>

@using (Html.BeginForm("Add", "MaestroDetalle", FormMethod.Post))
{
    <div class="row">
        <div class="form-group">
            @Html.LabelFor(d=>d.Cliente)
            @Html.TextBoxFor(d=>d.Cliente)
        </div>       
    </div>
    <hr />
    <div class="row">
        <div class="form-group" >
            Cantidad
            <input type="text" id="Cantidad"/>
            Nombre
            <input type="text" id="Nombre"/>
            Precio
            <input type="number" id="Precio"/>
            <input value="Agregar" type="button" onclick="AgregarConcepto(); return false;"/>
            @*se pone return false en este boton porque mas abajo hay un submit dentro y si no se pone se va a ser el submit y no el boton*@
        </div>
        
        <div id="divConceptos">
            <table id="tablaConceptos" style="width:100%">
                @*<thead>*@
                    <tr>
                        <th>Cantidad</th>
                        <th>Nombre</th>
                        <th>Precio unitario</th>
                        <th>Total</th>
                    </tr>
                @*</thead>
                <tbody>*@
                    
                @*</tbody>*@
            </table>

        </div>

        <div class="form-group">
            <input type="submit" value="Guardar" />
        </div>
    </div>
}

<script>
    var num = 0;
    function AgregarConcepto() {
        let Cantidad = document.getElementById("Cantidad").value;
        let Precio = document.getElementById("Precio").value;
        let Nombre = document.getElementById("Nombre").value;

        let Tabla = document.getElementById("tablaConceptos");
        let TR = document.createElement("tr");
        let TDCantidad = document.createElement("td");
        let TDNombre = document.createElement("td");
        let TDPrecio = document.createElement("td");
        let TDTotal = document.createElement("td");

        TR.appendChild(TDCantidad);
        TR.appendChild(TDNombre);
        TR.appendChild(TDPrecio);
        TR.appendChild(TDTotal);

        TDCantidad.innerHTML = Cantidad;
        TDNombre.innerHTML = Nombre;
        TDPrecio.innerHTML = Precio;
        TDTotal.innerHTML = parseFloat(Cantidad) * parseFloat(Precio);
        Tabla.appendChild(TR); //se agrega el TR a la tabla

        ////// agregamos el hidens
        let DivConceptos = document.getElementById("divConceptos");
        let HiddenIndex = document.createElement("input");
        let HiddenCantidad = document.createElement("input");
        let HiddenNombre = document.createElement("input");
        let HiddenPrecio = document.createElement("input");

        HiddenIndex.name = "Conceptos.Index";
        HiddenIndex.value = num;
        HiddenIndex.type = "hidden";
        HiddenCantidad.name = "Conceptos[" + num + "].Cantidad";
        HiddenCantidad.value = Cantidad;
        HiddenCantidad.type = "hidden";
        HiddenNombre.name = "Conceptos[" + num + "].Nombre";
        HiddenNombre.value = Nombre;
        HiddenNombre.type = "hidden";
        HiddenPrecio.name = "Conceptos[" + num + "].PrecioUnitario";
        HiddenPrecio.value = Precio;
        HiddenPrecio.type = "hidden";
        DivConceptos.appendChild(HiddenIndex);
        DivConceptos.appendChild(HiddenCantidad);
        DivConceptos.appendChild(HiddenNombre);
        DivConceptos.appendChild(HiddenPrecio);

        document.getElementById("Cantidad").value="";
        document.getElementById("Precio").value="";
        document.getElementById("Nombre").value = "";

        num++;
    }
</script>

MaestroDetalleMVC/MaestroDetalle_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>